-
  branches:
    only:
      - master

  configuration: Release

  platform:
      - Any CPU

  skip_commits:
    files:
        - .github/*

  image: Visual Studio 2017

  pull_requests:
    do_not_increment_build_number: false

  assembly_info:
    patch: true
    file: Source\Depressurizer\Properties\AssemblyInfo.cs
    assembly_version: $(APPVEYOR_REPO_COMMIT_MESSAGE)
    assembly_file_version: $(APPVEYOR_REPO_COMMIT_MESSAGE).$(APPVEYOR_BUILD_NUMBER)
    assembly_informational_version: $(APPVEYOR_REPO_COMMIT_MESSAGE)

  before_build: nuget restore Source/Depressurizer.sln

  artifacts:
  - path: Source\Depressurizer\bin\Release
    name: Depressurizer
    type: zip

  deploy:
  - provider: GitHub
    tag: v$(APPVEYOR_REPO_COMMIT_MESSAGE)
    release: Depressurizer v$(APPVEYOR_REPO_COMMIT_MESSAGE)
    auth_token:
      secure: zF7pNPToC088MA+tWs3v39Je50oYrGIPnLseI6ovxSum07d51AEdPTM4hDXSULn6
    draft: true
    artifact: /.*\.zip/
    force_update: true
    on:
      branch: master

-
  branches:
    except:
      - gh-pages

  configuration:
    - Debug
    - Release

  platform:
    - Any CPU

  skip_commits:
    files:
      - .github/*

  image: Visual Studio 2017

  pull_requests:
    do_not_increment_build_number: false

  before_build: nuget restore Source/Depressurizer.sln

  build:
    project: Source/Depressurizer.sln
    verbosity: quiet
