# branches to build
branches:
  # whitelist
  only:
    - master
    - dev
    - production

  # blacklist
  except:
    - gh-pages

# Skipping commits affecting specific files (GitHub only). More details here: /docs/appveyor-yml
skip_commits:
  files:
    - .github/*

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

assembly_info:
  patch: true
  file: src\Depressurizer\Properties\AssemblyInfo.cs
  assembly_version: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  assembly_file_version: $(APPVEYOR_REPO_COMMIT_MESSAGE).$(APPVEYOR_BUILD_NUMBER)
  assembly_informational_version: $(APPVEYOR_REPO_COMMIT_MESSAGE)

before_build: nuget restore src/Depressurizer.sln

configuration:
- Debug
- Release
platform:
- x86
- x64
- Any CPU

build:
  project: src/Depressurizer.sln
  verbosity: quiet

artifacts:
- path: src\Depressurizer\bin\$(platform)\Release
  name: Depressurizer-$(platform)
  type: zip

deploy:
- provider: GitHub
  tag: v$(APPVEYOR_REPO_COMMIT_MESSAGE)
  release: Depressurizer v$(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: uQq3zgS1DmLxFLeWwLMO5ojr7zsx6B35llWr2HxId1Fy1rOxjiUvN4p3rNn2sDdL
  draft: true
  artifact: /.*\.zip/
  force_update: true
  on:
    branch: master
