//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Depressurizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Depressurizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\appcache\appinfo.vdf.
        /// </summary>
        public static string AppInfoPath {
            get {
                return ResourceManager.GetString("AppInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Categorize ({0} Games).
        /// </summary>
        public static string AutoCat_ButtonLabel {
            get {
                return ResourceManager.GetString("AutoCat_ButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\7\remote\sharedconfig.vdf.
        /// </summary>
        public static string ConfigFilePath {
            get {
                return ResourceManager.GetString("ConfigFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Theo47/depressurizer.
        /// </summary>
        public static string DepressurizerHomepage {
            get {
                return ResourceManager.GetString("DepressurizerHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\Game Banners\{1}.jpg.
        /// </summary>
        public static string GameBannerPath {
            get {
                return ResourceManager.GetString("GameBannerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                     GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LICENSE {
            get {
                return ResourceManager.GetString("LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\config\localconfig.vdf.
        /// </summary>
        public static string LocalConfigPath {
            get {
                return ResourceManager.GetString("LocalConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\appcache\packageinfo.vdf.
        /// </summary>
        public static string PackageInfoPath {
            get {
                return ResourceManager.GetString("PackageInfoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\760\screenshots.vdf.
        /// </summary>
        public static string ScreenshotsFilePath {
            get {
                return ResourceManager.GetString("ScreenshotsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\userdata\{1}\config\shortcuts.vdf.
        /// </summary>
        public static string ShortCutsFilePath {
            get {
                return ResourceManager.GetString("ShortCutsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}/games?tab=all.
        /// </summary>
        public static string UrlCustomGameListHtml {
            get {
                return ResourceManager.GetString("UrlCustomGameListHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        public static string UrlCustomGameListXml {
            get {
                return ResourceManager.GetString("UrlCustomGameListXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/id/{0}?xml=1.
        /// </summary>
        public static string UrlCustomProfileXml {
            get {
                return ResourceManager.GetString("UrlCustomProfileXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcdn-a.akamaihd.net/steam/apps/{0}/capsule_sm_120.jpg.
        /// </summary>
        public static string UrlGameBanner {
            get {
                return ResourceManager.GetString("UrlGameBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}/games?tab=all.
        /// </summary>
        public static string UrlGameListHtml {
            get {
                return ResourceManager.GetString("UrlGameListHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}/games?tab=all&amp;xml=1.
        /// </summary>
        public static string UrlGameListXml {
            get {
                return ResourceManager.GetString("UrlGameListXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.howlongtobeatsteam.com/api/games/library/cached/all.
        /// </summary>
        public static string UrlHLTBAll {
            get {
                return ResourceManager.GetString("UrlHLTBAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/Theo47/depressurizer/releases/latest.
        /// </summary>
        public static string UrlLatestRelease {
            get {
                return ResourceManager.GetString("UrlLatestRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://steamcommunity.com/profiles/{0}?xml=1.
        /// </summary>
        public static string UrlSteamProfile {
            get {
                return ResourceManager.GetString("UrlSteamProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/.
        /// </summary>
        public static string UrlSteamStore {
            get {
                return ResourceManager.GetString("UrlSteamStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/app/{0}/.
        /// </summary>
        public static string UrlSteamStoreApp {
            get {
                return ResourceManager.GetString("UrlSteamStoreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /profile/avatarIcon.
        /// </summary>
        public static string XmlNodeAvatar {
            get {
                return ResourceManager.GetString("XmlNodeAvatar", resourceCulture);
            }
        }
    }
}
